name: 'Terraform plan on PR'

on:
  push:
  #pull_request:
    branches:
     # - main
     - '*'

permissions:
  id-token: write
  contents: read
  pull-requests: write


jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TF_VERSION: 1.5.7
    runs-on: ubuntu-latest
    environment: production
  
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: hashicorp/setup-terraform@v3
      
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
    - run: |
          terraform init
 
         
    - name: Terraform Plan
      id: plan
      run: terraform plan 
  
